#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export useful_skew=True
export hold_target_slack=0.005
export setup_target_slack=0.0
export order=setup-optmode.tcl,main.tcl

# Commands

ln -sf inputs/innovus-foundation-flow
innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
cd outputs
ln -sf ../checkpoints/design.checkpoint

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

