#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=accelerator

# Commands

cp inputs/adk/magicrc .magicrc
cp -L inputs/design.def.gz design.def.gz
gunzip design.def.gz
sed -i 's/\//____/g' design.def
magic -noconsole -dnull extract.tcl | tee def2spice.log

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

