#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export design_name=accelerator

# Debug

calibre -rve -lvs svdb

