#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=accelerator
export clock_period=20.0
export construct_path=/home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/construct.py
export adk=skywater-130nm-adk
export adk_view=view-standard

# Commands

echo "Design name      -- accelerator"
echo "Clock period     -- 20.0"
echo "ADK              -- skywater-130nm-adk"
echo "ADK view         -- view-standard"
echo
echo "Constructed from -- /home/users/jeffreyy/ee372/skywater-digital-flow/accelerator/design/construct.py"
echo

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

