#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export design_name=accelerator
export saif_instance=accelerator_tb/accelerator_inst
export analysis_mode=averaged
export zero_delay_simulation=False
export lib_op_condition=undefined
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,report-timing.tcl,report-power.tcl

# Debug

source debug.sh

