#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export order=fill-decap.tcl,main.tcl,generate-results.tcl,reporting.tcl

# Debug

innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl -log logs/debug.log

