#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=accelerator
export clock_period=20.0
export saif_instance=accelerator_tb/accelerator_inst
export flatten_effort=0
export topographical=True
export nthreads=16
export high_effort_area_opt=False
export gate_clock=True
export uniquify_with_design_name=True
export suppress_msg=False
export suppressed_msg=TFCHK-072,TFCHK-014,TFCHK-049,TFCHK-050,TFCHK-012,TFCHK-073,TFCHK-092,PSYN-651,PSYN-650
export order=designer-interface.tcl,setup-session.tcl,read-design.tcl,constraints.tcl,make-path-groups.tcl,compile-options.tcl,compile.tcl,generate-results.tcl,reporting.tcl

# Commands

bash run.sh

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

