#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD

# Commands

cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.sp              outputs/sky130_sram_1kbyte_1rw1r_32x256_8.sp
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lvs.sp          outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lvs.sp
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.v               outputs/sky130_sram_1kbyte_1rw1r_32x256_8.v
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lef             outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lef
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib outputs/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.gds             outputs/sky130_sram_1kbyte_1rw1r_32x256_8.gds
cp $SRAM_PATH/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db  outputs/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.db
sed -i '/SHAPE ABUTMENT/d' outputs/sky130_sram_1kbyte_1rw1r_32x256_8.lef

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

