#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/jeffreyy/ee372/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD

# Commands

cat rv_opcodes.sv dut/*.sv dut/*.v > outputs/design.v
cat rv_opcodes.sv dut/*.sv dut/*.v > outputs/design.vcs.v

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

